### ISSUE TITLE
APIfy Friend.ly

### ISSUE THREAD

**Issue by AlQaholic007** [AlQaholic007/Friend.ly#11]
**Is your feature request related to a problem? Please describe.**
We need to make API endpoints to enable users to post stuff, grant OAuth2, etc just via API calls

**Describe the solution you'd like**
All these API endpoints go in /api/v1 within routes

**Additional context**
This not only gives our app a wider user base but also enables us to write unit tests to see if different things work well in conjunction

**Comment by AlQaholic007** [comment]
@vidhi-mody any progess on this?

**Comment by AlQaholic007** [comment]
@vidhi-mody what is your status on this? Please update here

**Comment by vidhi-mody** [comment]
working on it
