### ISSUE TITLE
Take harmony rating into consideration for recommendations

### ISSUE THREAD

**Issue by AlQaholic007** [AlQaholic007/Friend.ly#14]
**Is your feature request related to a problem? Please describe.**
Earlier, we only considered the personality values for recommendations. Now we need to use a conjunction of the harmonic rating and the personality values for showing recommendations.

**Describe the solution you'd like**
The backend for managing recommendations has to be modified to take into account the harmonic rating as well. The flow has to be as follows: 
- group by or bucket the users by personality rating
- for users within the same bucket, take the ones with higher harmonic ratings

**Describe alternatives you've considered**
In the future, we will use a LOESS regressor to come up with optimal weights but currently, we do not have enough data to train a viable LOESS regressor

**Additional context**
![image](https://user-images.githubusercontent.com/55358652/76282617-345c6480-62be-11ea-9d9c-72c9b50da284.png)

**Comment by AlQaholic007** [comment]
@vrushti-mody is this in progress? I've got no updates on this?

**Comment by vrushti-mody** [comment]
I was supposed to work on Cypress testing when we last spoke. @vidhi-mody
please explain the code for harmonic rating for me to work on it.
